version: '3'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: sigma-chan
      MINIO_ROOT_PASSWORD: sigma-chan-dayo
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001;
      mkdir -p /data/.minio.sys/buckets;
      cp -r /policies/* /data/.minio.sys/;
      /usr/bin/minio server /data"
    volumes:
      - ./data:/export
      - ./minio/policies:/policies
      - ./minio/config:/root/.minio
    ports:
      - "9000:9999"
      - "9001:9001"
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nsakairi/getter-robo
    ports:
      - "5550:8888"
    container_name: getter-robo
    volumes:
      - "./sigma_chan_getter_robo/data:/home/sigma_chan/sigma_chan_getter_robo/data"
      - "./data:/home/sigma_chan/data"
    tty: true
    stdin_open: true
    networks:
      - app-net
    depends_on:
      - db
    links:
      - db
    networks:
      - app-net
    environment:
      - DISPLAY=${DISPLAY}
networks:
  app-net:
    driver: bridge
    

