apiVersion: batch/v1
kind: CronJob
metadata:
  name: getter-robo
spec:
  schedule: "00 06 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: getter-robo
            image: nsakairi/getter-robo@sha256:sha256:2a83dc7c758b9b3b965ff090f8edfb28ee92a29559272c8b0a54547e06a5a9dc
            #image: nsakairi/getter-robo@sha256:fee25e79a6ae725c0ac45630843b08eb17d256b45975a77f08884b2d6465a7a6
            #image: nsakairi/getter-robo@sha256:544264c665b6080ae4f0ee26261ea57c51d2b4accb82e986f1a0e0ceb886767d
            #image: nsakairi/getter-robo:latest
            env:
            - name: ENDPOINT_URL
              value: 192.168.1.194
            command: [python, main.py]
            #args: ['{"endpoint_url": "192.168.1.1", "storage": {"access_id": "sigma_chan", "access_key": "sigma_chan_dayo", "bucket": "getter_robo"}}']
            args: {
              "endpoint_url": "192.168.1.1", 
              "storage": {
                "access_id": "sigma_chan", 
                "access_key": "sigma_chan_dayo", 
                "bucket": "getter_robo"}
              }
            ports:
              - containerPort: 5550
          restartPolicy: OnFailure
