apiVersion: batch/v1
kind: Job
metadata:
  name: getter-robo
  labels:
    app: getter-robo
spec:
  template:
    spec:
      containers:
      - name: getter-robo
        image: nsakairi/getter-robo:latest
        command: [python, main.py]
        ports:
          - containerPort: 5550
        volumeMounts:
        - name: persistent-data-volume
          mountPath: /home/sigma_chan/data
      #restartPolicy: Never
      volumes:
      - name: persistent-data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        #fsGroup: 1000
        