apiVersion: batch/v1
kind: Job
metadata:
  name: getter-robo
  labels:
    app: getter-robo
spec:
  template:
    spec:
      containers:
      - name: getter-robo
        image: nsakairi/getter-robo@sha256:544264c665b6080ae4f0ee26261ea57c51d2b4accb82e986f1a0e0ceb886767d
        #sha256:b5aef7ca4154f2b10d4ea9682f2249fa62a4787aa256b9f8515382e935e633f5
        command: [python, main.py]
        ports:
          - containerPort: 5550
      restartPolicy: Never
