version: "3"
services:
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d ### initial directory
      - ./mysql/db:/var/lib/mysql ### parmanent directory
    image: getter-robo-db
    container_name: "getter-robo-db"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
