version: '3'

services:
  db:
    image: mysql:5.7
    container_name: getter-db-host
    environment:
      MYSQL_ROOT_PASSWORD: root  # root user password
      MYSQL_DATABASE: getter_db  # db name created initially
      MYSQL_USER: docker         # user named as docker
      MYSQL_PASSWORD: docker     # password for docker
      TZ: 'Asia/Tokyo'           # timezone seetting in a conainer
    ### setting to make the host paramanent. host_side: container_side
    volumes:
      - ./sigma_chan_db/db/data:/var/lib/mysql               # MySQL data
      - ./sigma_chan_db/db/my.conf:/etc/mysql/conf.d/my.cnf  # MySQL setting file
      - ./sigma_chan_db/db/sql:/docker-entrypoint-initdb.d   # db initialization script
    ### port-forwarding setting
    ### port no. is 3306 as usual
    ports:
      - "3306:3306"
    tty: true
    stdin_open: true
    networks:
      - app-net
  operator:
    build:
      context: ./operators
      dockerfile: Dockerfile
    ports:
      - "5550:8888"
    container_name: getter-db-operator
    volumes:
      - "./operators:/operators"
    tty: true
    stdin_open: true
    networks:
      - app-net
    depends_on:
      - db
    links:
      - db
    networks:
      - app-net
    environment:
      - DISPLAY=${DISPLAY}
networks:
  app-net:
    driver: bridge
    

